/**
 * Regenerate the README's autogenerated blocks:
 *
 * - **Examples table** — rendered from the same `@example` rows the tests run
 *   against ({@link extractExamples}). The result cells use direct, deterministic
 *   CDN links (no is.gd round-trip), so the table is reproducible from source alone.
 * - **CLI options** — the actual `mc-icons --help` output, rendered straight from
 *   the {@link main} command definition (no subprocess), so the docs can never
 *   drift from the real flags.
 *
 * Run with `pnpm gen:readme`. Pass `--check` to fail (non-zero exit) when the
 * README is stale instead of rewriting it — handy for CI.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import process from 'node:process'
import { renderUsage } from 'citty'
import { main } from '../cli.js'
import { PROJECT_ROOT } from '../lib/projectRoot.js'
import { extractExamples, IconizeRunner } from './examples.js'

const README = resolve(PROJECT_ROOT, 'README.md')

const EXAMPLES_START = '<!-- AUTOGEN:examples -->'
const EXAMPLES_END = '<!-- /AUTOGEN:examples -->'
const CLI_START = '<!-- AUTOGEN:cli -->'
const CLI_END = '<!-- /AUTOGEN:cli -->'

// eslint-disable-next-line no-control-regex
const ANSI = /\[[0-9;]*m/g

function escapeCell(s: string): string {
  return s.replace(/\|/g, '\\|')
}

/**
 * Replace the content between `start` and `end` markers with `content`.
 * Exits non-zero when either marker is missing.
 */
function replaceBlock(md: string, start: string, end: string, content: string): string {
  const startIdx = md.indexOf(start)
  const endIdx = md.indexOf(end)
  if (startIdx < 0 || endIdx < 0) {
    console.error(`README markers ${start} … ${end} not found`)
    process.exit(1)
  }
  return `${md.slice(0, startIdx + start.length)}\n\n${content}\n\n${md.slice(endIdx)}`
}

async function buildTable(): Promise<string> {
  const runner = new IconizeRunner()
  const rows: string[] = [
    '| Description | Capture | Result |',
    '|-------------|---------|--------|',
  ]

  for (const ex of extractExamples()) {
    const captures: string[] = []
    const icons: string[] = []
    for (const seg of ex.segments) {
      captures.push(`\`${seg.capture}\``)
      for (const { path, name } of await runner.run(seg.capture)) {
        const alt = name.replace(/[[\]]/g, '')
        const title = name.replace(/"/g, '\\"')
        icons.push(`![${alt}](${runner.repo}${path}.png "${title}")`)
      }
    }
    rows.push(
      `| ${escapeCell(ex.description)} | ${escapeCell(captures.join('<br/>'))} | ${icons.join('') || '—'} |`,
    )
  }
  return rows.join('\n')
}

/** The real `mc-icons --help` output, as a fenced code block. */
async function buildCliHelp(): Promise<string> {
  const help = (await renderUsage(main))
    .replace(ANSI, '')
    .split('\n')
    .map(line => line.replace(/\s+$/, '')) // drop citty's right-padding
    .join('\n')
    .trim()
  return `\`\`\`\n${help}\n\`\`\``
}

async function main_() {
  const [table, cli] = await Promise.all([buildTable(), buildCliHelp()])
  const md = readFileSync(README, 'utf8')

  let next = replaceBlock(md, EXAMPLES_START, EXAMPLES_END, table)
  next = replaceBlock(next, CLI_START, CLI_END, cli)

  if (process.argv.includes('--check')) {
    if (next !== md) {
      console.error('README is stale — run `pnpm gen:readme`')
      process.exit(1)
    }
    console.log('README up to date')
    return
  }

  if (next !== md) {
    writeFileSync(README, next)
    console.log('README regenerated')
  }
  else {
    console.log('README already up to date')
  }
}

main_()
